<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="DemoWebApplication2._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    
    <div>
        showing student data
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="StudentID" DataSourceID="SqlDataSource1" CellPadding="4" ForeColor="#333333" GridLines="None" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" PageSize="4">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
               
                <asp:BoundField DataField="StudentID" HeaderText="StudentID" ReadOnly="True" SortExpression="StudentID" />
                <asp:TemplateField HeaderText="StudentName" SortExpression="StudentName">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("StudentName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("StudentName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender" SortExpression="Gender">
                    <EditItemTemplate>
                        <asp:DropDownList runat="server" ID="ddgender">
                            <asp:listitem Text="Male" Value="M"></asp:listitem>
                            <asp:listitem Text="FeMale" Value="F" ></asp:listitem>
                        </asp:DropDownList>
                        <%--<asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Gender") %>'></asp:TextBox>--%>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="CityName" HeaderText="CityName" SortExpression="CityName" />
                <asp:BoundField DataField="ZipCode" HeaderText="ZipCode" SortExpression="ZipCode" />
                <asp:BoundField DataField="StateName" HeaderText="StateName" SortExpression="StateName" />
                <asp:BoundField DataField="CountryName" HeaderText="CountryName" SortExpression="CountryName" />
                <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                <asp:BoundField DataField="DOJ" HeaderText="DOJ" SortExpression="DOJ" />
                <asp:BoundField DataField="FatherName" HeaderText="FatherName" SortExpression="FatherName" />
                <asp:BoundField DataField="FatherOccupation" HeaderText="FatherOccupation" SortExpression="FatherOccupation" />
                <asp:BoundField DataField="MotherOccupation" HeaderText="MotherOccupation" SortExpression="MotherOccupation" />
                <asp:BoundField DataField="FatherMobileNumber" HeaderText="FatherMobileNumber" SortExpression="FatherMobileNumber" />
                <asp:BoundField DataField="MotherName" HeaderText="MotherName" SortExpression="MotherName" />
                <asp:BoundField DataField="MotherMobileNumber" HeaderText="MotherMobileNumber" SortExpression="MotherMobileNumber" />
                <asp:BoundField DataField="Address1" HeaderText="Address1" SortExpression="Address1" />
                <asp:BoundField DataField="Address2" HeaderText="Address2" SortExpression="Address2" />
                <asp:BoundField DataField="StudentPhoto" HeaderText="StudentPhoto" SortExpression="StudentPhoto" />
                <asp:BoundField DataField="FatherPhoto" HeaderText="FatherPhoto" SortExpression="FatherPhoto" />
                <asp:BoundField DataField="MotherPhoto" HeaderText="MotherPhoto" SortExpression="MotherPhoto" />
                <asp:BoundField DataField="EmailId" HeaderText="EmailId" SortExpression="EmailId" />
                <asp:BoundField DataField="Timings" HeaderText="Timings" SortExpression="Timings" />
                <asp:BoundField DataField="fees" HeaderText="fees" SortExpression="fees" />
                <asp:BoundField DataField="StudentSource" HeaderText="StudentSource" SortExpression="StudentSource" />
                <asp:BoundField DataField="AdmissionRemarks" HeaderText="AdmissionRemarks" SortExpression="AdmissionRemarks" />
                <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
                <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
            </Columns>
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:PlaySchoolConnectionString %>" 
            SelectCommand="SELECT StudentID, StudentName, Gender, CityName, ZipCode, StateName, CountryName, DOB, DOJ, FatherName, FatherOccupation, MotherOccupation, FatherMobileNumber, MotherName, MotherMobileNumber, Address1, Address2, StudentPhoto, FatherPhoto, MotherPhoto, EmailId, Timings, fees, StudentSource, AdmissionRemarks, status, UserName FROM vw_StudentDetails" 
         
            >

        </asp:SqlDataSource>
        

        </div>
   

</asp:Content>
